### ISSUE TITLE
"Failed to load plugin"

### ISSUE THREAD

**Issue by TheMathGuyd** [david-gorski/obsidian_front_matter_file_icons#2]
MacOS 12.3
Obsidian v0.14.2

Downloaded and copied to my plugins folder, but cannot enable the plugin.

Is there a risk of conflict with a core plugin? I tried disabling other community plugins but couldn't get it to work.

(I am most excited about this plugin)

**Comment by david-gorski** [comment]
👋  Glad to hear you're excited about my plugin. 

When you mention that you cannot enable the plugin, do you mean...

1. that you do not see the plugin in the installed community plugins section
2. that when you enable the plugin in that menu your icons do not appear

In case 1, I suspect that there is a problem with moving the documents into the plugins directory. You should end up with a plugins folder that looks like `/.obsidian/plugins/obsidian_front_matter_icons` and the `obsidian_front_matter_icons` folder contains the `package.json` amongst all the other files. Make sure the folder is unzipped.

In case 2, perhaps you have a theme that has some breaking changes. You could try turning off the theme if you have one on and restarting. Also note, that it won't do anything until you add the metadata to your files, and updating the metadata can be a bit laggy due to how obsidian API works. I mostly just open and close the file to refresh the icon I specify.

Hopefully, either of those answers help, or if not let me know some more details on what's going on. There should not be a conflict with any core plugins.

**Comment by TheMathGuyd** [comment]
Hello!
I already have the master unzipped and placed in the plugins directory. So case 1 will not apply.

**Comment by TheMathGuyd** [comment]
Sorry I accidentally tapped my screen before finishing my message. I have also tried turning off all snippets and themes. Still the same error.
This afternoon, I will try with a fresh vault and on another OS

---
Couldn't wait, so I tried another vault (still on MacOS 12.3) and no luck. When I try to toggle on the Frontmatter Icons plugin in the "Community Plugins", it fails in the same way

**Comment by david-gorski** [comment]
Ah. I suspect this will solve it: add an "obsidian-emoji-file-icons" entry to .obsidian/community-plugins.json

**Comment by david-gorski** [comment]
Ah. I have led you astray. Just went through this myself to see. Grab the 3 files attached to the 1.0.1 release: main.js, manifest.json, and styles.css. Place these into a folder in the .obsidian/plugins folder. The source does not contain the compiled js files.

**Comment by TheMathGuyd** [comment]
Many thanks!!
Swapping those out for the old contents worked perfectly. 
I am now happily testing this out. It works very consistent on desktop in the File Explorer and replaced the generic "page" icon in the top left of open panes. If you don't mind, I will open another issue regarding applying these icons to notes pinned to the sidebar.

(Note for future readers, quit and re-open obsidian to see icons change)

**Comment by htsplex** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
natsu2711, @royds4, @Dcomplexity, @sepehrkiller, @dingrn, @mick20, @cbnolok, @dcarina, @austinvach, @DerekMarcinyshyn, @xiaoguangge, @AndriianChestnykh, @JeffLabonte, @xrcyz, @ldjdsc, @ImsMoon, @harrisrobin, @paulolimac, @btc824, @triThirty, @gavinwang-au, @darkrabel, @vinopm, @natanschultz, @WhisperRoot, @shijianhuai, @4TsirhC, @android-programmer, @TexasBullet26, @DanisFabric, @imghasemi, @Deval1807, @AntonioRossi, @srinikandula, @supremex04, @qfarhan, @tangyuan233, @adityasaxena, @rohankumar997, @Alpha2J, @ultrazhangster, @thaddeusreid, @kijwamoko, @AzureLeon1, @kthom91, @WayneDu98, @xulis, @Liuguanli, @0xcryptodad, @rodalbert
